
# model parameter
embedding_size: 1024 # fix as 384!

# Mips parameters
hash_num : 1000
m: 30
ranking_size : 5
r: 15

hash_ft_path: 'gen_ids/hash_ft.pickle'
hash_table_path: 'gen_ids/hash_table.pickle'