# Generated by Django 4.2 on 2023-05-07 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("content", models.CharField(max_length=400)),
                ("status", models.CharField(max_length=12)),
                ("lecture_name", models.CharField(max_length=24)),
                ("lecture_slide", models.IntegerField()),
                ("postBy", models.CharField(max_length=12)),
                ("postDate", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.CharField(max_length=400)),
                ("owner_accepted", models.IntegerField()),
                ("admin_accepted", models.IntegerField()),
                ("postBy", models.IntegerField()),
                ("postDate", models.DateTimeField(auto_now=True)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="qa_app.question",
                    ),
                ),
            ],
        ),
    ]
